### ISSUE TITLE
Release type in springboot uses version also

### ISSUE THREAD

**Issue by piyush1594** [fabric8-launcher/launcher-booster-catalog#187]
If you see the release type of spring-boot boosters here https://github.com/fabric8-launcher/launcher-booster-catalog/tree/master/spring-boot You will see the name is like `version+type(community or redhat)`

This is not in the case of vertex here https://github.com/fabric8-launcher/launcher-booster-catalog/tree/master/vert.x and wildfly here https://github.com/fabric8-launcher/launcher-booster-catalog/tree/master/wildfly-swarm They are just community or redhat.

We are using the booster.yml of spring boot boosters in FMP regression test. We are fetching the yaml from GitHub URL and this gives us the probability of breaking whenever the version of spring boot booster will change. Is there any specific reason behind this? or Is it possible to change them to community or redhat

Thanks

**Comment by Ladicek** [comment]
CC @metacosm @geoand

**Comment by metacosm** [comment]
Hi @piyush1594,

The reasoning is that we will probably soon start supporting SB 2.0 as well. We therefore need to be able to differentiate between Spring Boot versions.

**Comment by piyush1594** [comment]
Hey @metacosm 

Agree with the points that there is a reason behind this but my point is is it possible to use a static name in place of dynamic like the folder name will change in near future if new version release happen.

Like you can use SB1-redhat and later SB2-redhat. My problem is we are using a name which will change. If the folder name will not change I don't have any problem.

Thanks

**Comment by metacosm** [comment]
Hi @piyush1594,
Sorry but I'm not sure I understand what you're trying to accomplish. While we could use static folder name, I'd rather keep explicit ones so that we avoid any confusion as to which is which. Could you please explain what you're trying to accomplish in greater details (an example of the scenario that causes an issue would be great) so that we can see how to deal with the issue appropriately?

Thanks in advance.

**Comment by piyush1594** [comment]
Hey @metacosm 

I read booster.yaml file for three boosters - configmap, crud, and HTTP. Like for the case of configmap, we are fetching the URL and git ref from booster.yaml whose link is https://github.com/fabric8-launcher/launcher-booster-catalog/blob/master/spring-boot/1.5.10-redhat/configmap/booster.yaml

If you see the URL, there is a possibility like whenever you will release 1.5.11 version. It will break if you change the folder name also that seems like will be changed. This will lead to breaking the regression tests of FMP. I don't have any problem if the `1.5.10-redhat` thing will not change. But it will change then either we need to maintain this regularly just changing the folder name or we can make this static if possible. 

This will not happen in the case of vertx and wildfly. Like URL for vertx configmap booster.yaml is https://github.com/fabric8-launcher/launcher-booster-catalog/blob/master/vert.x/redhat/configmap/booster.yaml

Hope you understand. If not I will give more try.

Thanks

**Comment by metacosm** [comment]
@piyush1594 

I don't understand what's the issue with `current` and `previous`? These will be stable, regardless of the runtime version…

**Comment by piyush1594** [comment]
@metacosm 

What I understand from current and previous is like you will maintain two like 1.5.10-redhat and 1.5.11-redhat. Then whenever you will release 1.5.12 then 1.5.10 will go and we need to maintain further.

Maybe I got wrong. We are doing this to always use the version which is used in OSIO for our regression tests.

**Comment by metacosm** [comment]
@piyush1594 
What I meant is that https://github.com/fabric8-launcher/launcher-booster-catalog/blob/master/spring-boot/1.5.10-redhat/configmap/booster.yaml would become https://github.com/fabric8-launcher/launcher-booster-catalog/blob/master/spring-boot/current-redhat/configmap/booster.yaml. When/if we start supporting Spring Boot 2, then `current` will probably change to point to it in `booster.yaml` and we will add `previous-redhat` to point to `1.5.10` but the URL will stay stable, similarly to what's going on with the other runtimes.

**Comment by piyush1594** [comment]
Thanks @metacosm This looks good to me. Thanks for clarifying and considering. Any ETA for this? Like how much time it may take to discuss within the team and finalize it. Thanks

**Comment by metacosm** [comment]
ETA: probably not before next week as we have quite a lot on our plates at the moment.

**Comment by piyush1594** [comment]
Thanks @metacosm 

No hurry. Will check this place later. Thanks for this.

**Comment by piyush1594** [comment]
Thanks for considering this and fixing
