### ISSUE TITLE
Introduce a specific metadata entry for boosters enabled in OSIO 

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-booster-catalog#242]
Making OSIO as a `runsOn` value is becoming problematic with new boosters. We decided that the best is for the Booster metadata to have a `osio.enabled: true` flag on boosters that should appear in OSIO and change the frontend code to query on that instead

**Comment by gastaldi** [comment]
cc @animuk @ravsa

**Comment by gastaldi** [comment]
```
metadata:
   osio:
      supported: true
```

**Comment by quintesse** [comment]
Why the section @gastaldi ? Are you expecting more OSIO-related properties?
