### ISSUE TITLE
Add a logo to Spring Boot runtime

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-booster-catalog#328]
We should add a logo to Spring Boot so it looks better in the frontend

**Comment by gastaldi** [comment]
@fabric8-launcher/runtime-spring-boot

**Comment by gastaldi** [comment]
@metacosm @jclingan asked to remove some time ago, but we never added a replacement

**Comment by geoand** [comment]
Should we add the snowdrop logo?

**Comment by gastaldi** [comment]
@geoand that's not a bad idea, mind sending a PR?

**Comment by geoand** [comment]
The problem is that I don't know where to find the proper icon 😂

**Comment by gastaldi** [comment]
I think we have one in the launcher-creator-backend repository, let me check

**Comment by gastaldi** [comment]
@geoand we have this: https://github.com/fabric8-launcher/launcher-creator-backend/blob/master/lib/core/catalog/enums.json#L39 but maybe it would be nice to find a SVG version of it

**Comment by gastaldi** [comment]
Logos are in http://design.jboss.org/snowdrop/

**Comment by geoand** [comment]
Good to know! How would you like to proceed?

**Comment by gastaldi** [comment]
Send a PR to the repository changing the `metadata.yaml` by adding the `icon` property. I'll give you the honor :wink:

**Comment by geoand** [comment]
Will do 😁
