### ISSUE TITLE
Remove OSIO-specific boosters

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-booster-catalog#333]
OSIO is no longer available, and now it is time to remove the boosters and configurations that were created specifically for it

CC: @fabric8-launcher/runtimes

**Comment by lance** [comment]
@gastaldi which boosters were specifically created for OSIO?

**Comment by gastaldi** [comment]
@lance some runtimes had to create a separate version of the configmap booster, for example:  https://github.com/fabric8-launcher/launcher-booster-catalog/tree/master/spring-boot/previous-osio

**Comment by gastaldi** [comment]
@geoand can I ask you or anyone in your team to remove the OSIO specific:SB example from the catalog?

**Comment by geoand** [comment]
@gastaldi certainly, not a problem
