### ISSUE TITLE
Catalog wasn't republished with Fuse 7.8 updates

### ISSUE THREAD

**Issue by apupier** [fabric8-launcher/launcher-booster-catalog#414]
see https://github.com/fabric8-launcher/launcher-booster-catalog/pull/410#issuecomment-812876671

**Comment by quintesse** [comment]
Release created: https://github.com/fabric8-launcher/launcher-booster-catalog/releases/tag/v143 and confirmed that 7.8 appears in the list (although not as the first/preferred option). Can you confirm @apupier ?

**Comment by apupier** [comment]
I can now see it at last position:

**Comment by apupier** [comment]
thanks @quintesse
